### ISSUE TITLE
doesnt work in IE11

### ISSUE THREAD

**Issue by medmen** [cosmocode/dokuwiki-plugin-tablelayout#21]
Sorry to report this, buit i'm forced to use IE11 at work. Table-layout plugin does not show any items there (works fine in Firefox on the same Computer). The problem seems to reside in js .repeat() function: Object doesn't support property or method 'repeat' - in the following code:
`function addSearchSortRow($table,numHeaderRows,columnCount){
var $searchSortRow=jQuery('<tr class="searchSortRow">'+'<th><div></div></th>'.repeat(columnCount)+'</tr>');
var $lastHeaderRow;`

would love to see this fixed but i dont have time to dig deeper right now :(

**Comment by splitbrain** [comment]
won't fix
